# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ln', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=49),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('removed', 'Removed'), ('no_active', 'No active'), ('active', 'Active')], default='no_active', max_length=15),
        ),
    ]
